### ISSUE TITLE
not supported in new version of exo player

### ISSUE THREAD

**Issue by theRemoter** [iambaljeet/VideoPreLoading#4]
Hello

thanks for the article. I've tried to implement it and to use it in the upgraded version of exoplayer (2.13) but many of the methods signatures are different and there is no support now for CacheUtil.

What changes should I do to support new version of exo player?

thanks

**Comment by iambaljeet** [comment]
Upgraded dependencies and code

https://github.com/iambaljeet/VideoPreLoading/pull/5
