### ISSUE TITLE
Video preload not work properly

### ISSUE THREAD

**Issue by mtamoon** [iambaljeet/VideoPreLoading#7]
video preload not work, it should be like preload the video in background is 5 sec or 10 sec of the video, in this way user data will consume less. you have told over a call me you will add few lines on code for this but still not added i am waiting for this bro please add this as soon as possible. love you

**Comment by iambaljeet** [comment]
Hello. please don't create issues for feature requests and to preload a specific length of video you can pass the length in DataSpec() along with video URI.

https://github.com/iambaljeet/VideoPreLoading/blob/d556a3c6d8186a986d3111d7d35a012a08dd9ed5/app/src/main/java/com/app/videopreloading/service/VideoPreLoadingService.kt#L65
